- examples/chat/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- examples/llm/mock/main.go
- examples/pipeline/chat/main.go
- examples/pipeline/memory/main.go
- examples/pipeline/openai/main.go
- examples/pipeline/simple/main.go
- llm/mock/mock.go
- llm/openai/openai.go
- pipeline/lmm.go
- pipeline/pipeline.go
> passing context to llms

- chat/chat.go
- chat/chat_test.go
- examples/prompt/hello/main.go
- pipeline/lmm.go
- prompt/prompt.go
- prompt/template.go
- prompt/template_test.go
- prompt/whisper.go
Issue: #25 
This PR refactors prompt interface
> chore: refactor prompt interface

- decoder/decoder_test.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- textsplitter/recursiveTextSplitter_test.go
> chore: add more test and some fixes

- examples/embeddings/knowledge_base/kb/README.md
- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- index/index.go
- index/pinecone.go
- index/simpleVectorIndex.go
> chore: add batchupsert refactor code

- chat/chat.go
- embedder/embedding.go
- embedder/openai/openai.go
- index/index.go
- index/pinecone.go
- index/simpleVectorIndex.go
- llm/openai/openai.go
- loader/textloader.go
- pipeline/pipeline.go
- pipeline/splitter.go
> chore: add errors

- examples/pipeline/openai/main.go
- llm/openai/openai.go
> chore: add openai callback usage

- chat/chat.go
- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- examples/llm/mock/main.go
- examples/prompt/hello/main.go
- examples/prompt/simple/main.go
- examples/prompt/whisper/main.go
- pipeline/lmm.go
- pipeline/pipeline.go
- prompt/prompt.go
- prompt/template.go
- prompt/template_test.go
- prompt/whisper.go
> chore: replace Prompt() method with String()

- document/document.go
- examples/pipeline/openai/main.go
- index/pinecone.go
- llm/openai/openai.go
- loader/textloader.go
- textsplitter/recursiveTextSplitter.go
- textsplitter/recursiveTextSplitter_test.go
- types/types.go
> chore: add types.Meta for metadata

- examples/embeddings/knowledge_base/kb/README.md
- examples/embeddings/knowledge_base/main.go
- loader/pdfloader.go
> chore: add pdf loader

- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- examples/pipeline/chat/main.go
- examples/pipeline/openai/main.go
- examples/pipeline/splitter/main.go
- llm/openai/openai.go
> chore: add stop sequence and refactor code

- examples/embeddings/pinecone/main.go
- go.mod
- go.sum
- index/pinecone.go
> chore: create pinecone index if required

- embedder/openai/openai.go
- index/pinecone.go
> chore: add concurrent embedding

- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- loader/directory.go
- loader/loader.go
- loader/pdf_to_text.go
- loader/pubmed.go
- loader/text.go
- textsplitter/recursiveTextSplitter.go
> chore: refactor loaders and splitters

- chat/chat_test.go
- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/simpleVector/main.go
- examples/pipeline/chat/main.go
- examples/pipeline/memory/main.go
- examples/pipeline/openai/main.go
- examples/pipeline/simple/main.go
- examples/pipeline/splitter/main.go
- examples/prompt/chat/main.go
- examples/prompt/hello/main.go
- pipeline/qatube.go
- prompt/template.go
- prompt/template_test.go
> chore: refactor prompt template

- examples/pipeline/splitter/main.go
- pipeline/splitter.go
> chore: refactor splitter

- examples/loader/whispercpp/main.go
- loader/whispercpp.go
> feat: add whispercpp loader

- examples/loader/libreoffice/main.go
- loader/libreoffice.go
- loader/loader.go
- loader/whispercpp.go
> feat: add libreoffice loader

- examples/loader/whisper/main.go
- loader/whisper.go
- loader/whispercpp.go
> feat: add whisper loader

- .gitignore
- examples/llm/llamacpp/main.go
- llm/llamacpp/llamacpp.go
> feat: add llamacpp

- embedder/llamacpp/llamacpp.go
- examples/embeddings/llamacpp/main.go
- llm/llamacpp/llamacpp.go
- loader/libreoffice.go
- loader/whispercpp.go
> chore add lamacpp embedder

- examples/loader/csv/main.go
- loader/csv.go
> feat: add csv loader

- examples/pipeline/callbacks/main.go
- pipeline/pipeline.go
- pipeline/tube.go
> feat: add pipeline callbacks

- examples/llm/huggingface/conversational/main.go
- llm/huggingface/conversational.go
- llm/huggingface/http.go
- llm/huggingface/huggingface.go
- llm/huggingface/shared.go
> feat: support conversational hugging face

- examples/llm/huggingface/textgeneration/main.go
- llm/huggingface/conversational.go
- llm/huggingface/http.go
- llm/huggingface/huggingface.go
- llm/huggingface/shared.go
- llm/huggingface/textgeneration.go
> feat: implement huggingface textgeneration

- examples/loader/hf_image_to_text/main.go
- loader/hf_image_to_text.go
> feat: add HF image to text loader

- examples/loader/hf_speech_recognition/main.go
- loader/hf_speech_recognition.go
> feat: add HF speech recognition loader

- embedder/huggingface/feature_extraction.go
- embedder/huggingface/http.go
- embedder/huggingface/huggingface.go
- examples/embeddings/huggingface/main.go
> feat: add hugginface sentence transformer embedder

- examples/transformer/dalle/main.go
- go.mod
- go.sum
- transformer/dall-e.go
> feat: implement dall-e transformer

- embedder/openai/openai.go
- llm/openai/openai.go
- loader/whisper.go
- prompt/whisper.go
- transformer/dall-e.go
issue: #81 
Suggestion: [here](https://github.com/henomis/lingoose/discussions/85)
> chore: add withClient to packages using openai

- examples/pipeline/history/main.go
- history/history.go
- pipeline/pipeline.go
- pipeline/tube.go
issue: #91 
This PR adds history to a LLM in a pipeline
> feat: add llm history

- chat/chat.go
- examples/chat/functions/main.go
- llm/openai/function.go
- llm/openai/openai.go
> chore: refactor function call messages

- examples/chat/functions/main.go
- llm/openai/function.go
- llm/openai/openai.go
> chore: refactor called function name

- llm/openai/openai.go
> chore: add finishReason

- examples/transformer/visual-question-answering/main.go
- transformer/visual-question-answering.go
> Feat add visual question answering transformer

- examples/loader/youtube-dl/main.go
- loader/youtube-dl.go
> feat add youtube-dl loader

- examples/llm/huggingface/textgeneration/main.go
- examples/llm/openai/batch/main.go
- llm/huggingface/huggingface.go
- llm/huggingface/textgeneration.go
- llm/openai/openai.go
> Feat Add llm batch completion

- document/document.go
- examples/transformer/cohere-rerank/main.go
- transformer/cohere-rerank.go
- types/types.go
> Add Document methods and improve rerank

- embedder/cohere/cohere.go
> Feat Add cohere embeddings

- examples/llm/openai/localai/main.go
> chore: add localai example

- README.md
> chore: fix README example

- README.md
> chore: refactor readme

- embedder/huggingface/http.go
- embedder/huggingface/huggingface.go
- llm/huggingface/http.go
- llm/huggingface/huggingface.go
> Chore Add custom http client support to HF api

- index/simpleVectorIndex/simpleVectorIndex.go
> Chore Fix load() in SimpleVectorIndex

- README.md
- examples/embeddings/knowledge_base/main.go
- examples/embeddings/pinecone/main.go
- examples/embeddings/qdrant/main.go
- examples/embeddings/simpleVector/main.go
- examples/embeddings/simplekb/main.go
- index/index.go
- index/pinecone/pinecone.go
- index/qdrant/qdrant.go
- index/simpleVectorIndex/simpleVectorIndex.go
> Chore/116 refactor indexes Query and Search

- index/pinecone/pinecone.go
- index/qdrant/qdrant.go
- index/simpleVectorIndex/simpleVectorIndex.go
> chore Add an index method to insert a vector

- README.md
- examples/embeddings/simplekb/main.go
- index/retriever/retriever.go
- pipeline/qa/qa.go
> Feat Implement index retriever

- examples/embeddings/simplekb/main.go
- pipeline/qa/qa.go
> Feat Add new QA pipeline mode refine

- pipeline/sql/sql.go
> fix linting

- examples/embeddings/jsondb/main.go
- examples/embeddings/knowledge_base/main.go
- examples/embeddings/simplekb/main.go
- examples/llm/cache/main.go
- index/index.go
- index/option/option.go
- index/vectordb/jsondb/jsondb.go
> Feat Add index insert data callback

- examples/embeddings/postgres/main.go
- index/vectordb/postgres/postgres.go
- index/vectordb/redis/redis.go
> Feat Implement postgres as vector storage

- pipeline/qa/qa.go
> Fix QA pipeline missing initialization in WithPrompt

- examples/transformer/hf-text-to-image/main.go
- transformer/hf-text-to-image.go
> Chore Add HF text to image models support

- examples/llm/ollama/multimodal/main.go
- llm/ollama/api.go
- llm/ollama/formatter.go
- llm/ollama/ollama.go
> chore Add ollama vision

- assistant/assistant.go
- assistant/prompt.go
- examples/assistant/main.go
- llm/cohere/formatter.go
> Chore Give an indentity to the assistant

- examples/llm/groq/main.go
- examples/llm/localai/main.go
- llm/groq/groq.go
- llm/localai/localai.go
> chore: add localai and groq llm wrapper

- docs/content/reference/linglet.md
- docs/content/reference/llm.md
- docs/content/reference/rag.md
- examples/linglet/qa/main.go
- examples/rag/subdocument/main.go
- linglet/qa/prompt.go
- linglet/qa/qa.go
- llm/ollama/formatter.go
- llm/ollama/ollama.go
- rag/sub_document.go
> Chore Add qa linglet

- examples/llm/antropic/multimodal/main.go
- examples/llm/antropic/stream/main.go
- llm/antropic/antropic.go
- llm/antropic/api.go
- llm/antropic/formatter.go
> feat: add anthropic support

- .github/PULL_REQUEST_TEMPLATE.md
> fix documentation

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/content/config.md
- docs/layouts/_default/single.html
- docs/layouts/partials/version-banner.html
- examples/llm/groq/main.go
- llm/groq/groq.go
> fix: groq api key env var

- llm/antropic/antropic.go
- llm/cohere/cohere.go
- llm/groq/groq.go
- llm/localai/localai.go
- llm/observer/observer.go
- llm/ollama/ollama.go
- llm/openai/openai.go
> Add observer to all the llms

- README.md
> update readme  adding blog posts 

- examples/observer/langfuse/openai/main.go
- llm/antropic/antropic.go
- llm/cohere/cohere.go
- llm/observer/observer.go
- llm/ollama/ollama.go
- llm/openai/openai.go
- observer/observer.go
> Refactor observer

- assistant/assistant.go
- examples/observer/assistant/main.go
- observer/langfuse/formatter.go
- observer/observer.go
- rag/rag.go
- rag/rag_fusion.go
- rag/sub_document.go
> Implement assistant and rag observer span

- assistant/assistant.go
- embedder/cohere/cohere.go
- embedder/huggingface/huggingface.go
- embedder/nomic/nomic.go
- embedder/observer/observer.go
- embedder/ollama/ollama.go
- embedder/openai/openai.go
- embedder/voyage/voyage.go
- examples/observer/assistant/main.go
- examples/observer/linglet/qa/main.go
- examples/observer/openai/main.go
- llm/antropic/antropic.go
- llm/cohere/cohere.go
- llm/observer/observer.go
- llm/ollama/ollama.go
- llm/openai/openai.go
- observer/observer.go
- rag/rag.go
- rag/rag_fusion.go
- rag/sub_document.go
> Store observer in context

- assistant/assistant.go
- assistant/prompt.go
- llm/openai/function.go
> fix: openai WithTools pointer receiver
